# Generated by Django 2.1.4 on 2019-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0004_auto_20190102_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('CA', 'CANADA'), ('US', 'USA')], max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
