# Generated by Django 2.1.4 on 2019-01-03 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0005_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('Plant', 'Plant'), ('DataCenter', 'Data Center'), ('Yard', 'Yard'), ('DistributionCenter', 'Distribution Center'), ('HeadOffice', 'Head Office')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
