# Generated by Django 2.1.4 on 2019-01-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0007_auto_20190103_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
