# Generated by Django 2.1.4 on 2019-01-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0008_auto_20190103_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('Plant', 'Plant'), ('DataCenter', 'Data Center'), ('Yard', 'Yard'), ('DistributionCenter', 'Distribution Center'), ('HeadOffice', 'Head Office')], max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.CharField(choices=[('CA', 'CANADA'), ('US', 'USA')], max_length=10),
        ),
    ]
