# Generated by Django 2.1.4 on 2019-01-03 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0012_auto_20190103_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='entity',
            field=models.CharField(choices=[('Capex', 'Capex'), ('Opex', 'Opex')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='glaccount',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='IFApp.Glaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='monthlyCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='reference',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='renewalDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
