# Generated by Django 2.1.4 on 2019-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0014_contract_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='noticePeriod',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
