# Generated by Django 2.1.4 on 2019-01-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0016_contract_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='noticePeriod',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
