# Generated by Django 2.1.4 on 2019-01-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFApp', '0021_auto_20190117_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='last_user_modify',
        ),
        migrations.RemoveField(
            model_name='glaccount',
            name='last_user_modify',
        ),
        migrations.RemoveField(
            model_name='site',
            name='last_user_modify',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='last_user_modify',
        ),
    ]
